
package com.jollyclass.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceHandlerService", targetNamespace = "http://webservice.jollyclass.com/", wsdlLocation = "http://172.16.2.22:5567/WebService?wsdl")
public class WebServiceHandlerService
    extends Service
{

    private final static URL WEBSERVICEHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEHANDLERSERVICE_EXCEPTION;
    private final static QName WEBSERVICEHANDLERSERVICE_QNAME = new QName("http://webservice.jollyclass.com/", "WebServiceHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.2.22:5567/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEHANDLERSERVICE_WSDL_LOCATION = url;
        WEBSERVICEHANDLERSERVICE_EXCEPTION = e;
    }

    public WebServiceHandlerService() {
        super(__getWsdlLocation(), WEBSERVICEHANDLERSERVICE_QNAME);
    }

    public WebServiceHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEHANDLERSERVICE_QNAME, features);
    }

    public WebServiceHandlerService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEHANDLERSERVICE_QNAME);
    }

    public WebServiceHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEHANDLERSERVICE_QNAME, features);
    }

    public WebServiceHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceHandler
     */
    @WebEndpoint(name = "WebServiceHandlerPort")
    public WebServiceHandler getWebServiceHandlerPort() {
        return super.getPort(new QName("http://webservice.jollyclass.com/", "WebServiceHandlerPort"), WebServiceHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceHandler
     */
    @WebEndpoint(name = "WebServiceHandlerPort")
    public WebServiceHandler getWebServiceHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.jollyclass.com/", "WebServiceHandlerPort"), WebServiceHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEHANDLERSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEHANDLERSERVICE_EXCEPTION;
        }
        return WEBSERVICEHANDLERSERVICE_WSDL_LOCATION;
    }

}
